node('maven') {
	// define commands
    def mvnCmd = "mvn -f /tmp/workspace/helloworld-sample-pipeline/OpenShiftHelloWorldServlet/pom.xml"
    stage('Build') {
         echo 'Building....'
         //git 'https://github.com/Eldurn/OpenShiftTests.git'
         //sh "${mvnCmd} clean install -DskipTests=true"
         sh "${mvnCmd} compile"
         
    }
    stage('Test') {
        echo 'Testing....'
        
        sh "${mvnCmd} test"
    }
    stage('Deploy') {
   	    echo 'Deploying....'
		
    } 
}