node('maven') {
    stage('Build') {
         echo 'Building....'
         
         
    }
    stage('Test') {
        echo 'Testing....'
        git 'https://github.com/Eldurn/OpenShiftTests.git'
        sh "mvn -f /tmp/workspace/helloworld-sample-pipeline/OpenShiftHelloWorldServlet/pom.xml test"
    }
    stage('Deploy') {
   	    echo 'Deploying....'
		openshiftDeploy depCfg: 'jws-app', verbose: 'false', waitTime: ''
		openshiftScale depCfg: 'jws-app', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true'
    } 
}